### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mdjnelson** [catalyst/moodle-local_submissionrestict#7]
`moodle-local_submissionrestict` should be `moodle-local_submissionrestrict`, `restict` should be `restrict`. The spelling `submissionrestict` is used throughout the whole codebase which ideally should be changed as well.

**Comment by dmitriim** [comment]
thanks @mdjnelson Good catch.
Renaming basically means a different plugin. As it's already installed that could be an issue. Any ideas about how to deal with that?

**Comment by danmarsden** [comment]
this does feel like something I would probably reject a moodle.org plugins db submission on... especially for one of our plugins. there's no easy way to rename something that is already installed - hopefully it's not installed in many places?

**Comment by dmitriim** [comment]
It's on one prod site and few tests sites at the moment. So not that bad...

**Comment by mdjnelson** [comment]
You could create another repository called `moodle-local_submissionrestrict` which is just a copy of this but with the typo fixed in the repository name and in the code and then move things across. Once all is moved delete this repo.

**Comment by dmitriim** [comment]
I mean dealing with that in the prod site :) haha But thanks for your advise.

**Comment by mdjnelson** [comment]
Well wouldn't what I say fix it in `prod` as well? Change `.gitmodules` and wait for that to propagate on all servers (or whatever I am not a devops haha) and once it has you can safely delete this repo. In the mean time it won't break prod as both URLs are valid until you delete this one.

**Comment by mdjnelson** [comment]
Actually it would be a bit more difficult than that since you have the folder in the `wwwroot`. So, all I can say is good luck :D.

**Comment by dmitriim** [comment]
Fixed in https://github.com/catalyst/moodle-local_submissionrestrict
